package com.sphereon.sdk.pdf.stamper.model;

public enum StampType {
    BARCODECOMPONENT,
    BLOCKCHAINPROOFCOMPONENT,
    CANVASCOMPONENT,
    HYPERLINKCOMPONENT,
    IMAGECOMPONENT,
    LINECOMPONENT,
    PDFSIGNATURECOMPONENT,
    TEXTCOMPONENT
}
