/*
 * PDF stamper
 * The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements.    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 1.0
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.pdf.stamper.api;

import com.sphereon.sdk.pdf.stamper.handler.ApiException;
import com.sphereon.sdk.pdf.stamper.model.ContentRequest;
import com.sphereon.sdk.pdf.stamper.model.ContentResponse;
import com.sphereon.sdk.pdf.stamper.model.ErrorResponse;
import com.sphereon.sdk.pdf.stamper.model.PdfStamperJobRequest;
import com.sphereon.sdk.pdf.stamper.model.PdfStamperJobResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SynchronousApi
 */
@Ignore
public class SynchronousApiTest {

    private final SynchronousApi api = new SynchronousApi();

    
    /**
     * Execute a synchronous stamp job with a content request/response.
     *
     * Execute a synchronous stamp job using the given configId. Header parameters will be parsed for additional template variables.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void syncJobContentTest() throws ApiException {
        ContentRequest contentRequest = null;
        ContentResponse response = api.syncJobContent(contentRequest);

        // TODO: test validations
    }
    
    /**
     * Execute a synchronous stamp job with a streamlocation.
     *
     * Execute a synchronous stamp job using the given configId. Header parameters will be parsed for additional template variables.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void syncJobStreamLocationTest() throws ApiException {
        PdfStamperJobRequest jobRequest = null;
        PdfStamperJobResult response = api.syncJobStreamLocation(jobRequest);

        // TODO: test validations
    }
    
}
