/**
 * PDF stamper
 * The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements. The API also supports digital signatures (blue bar), blockchain registrations and filling out forms    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 1.0
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKPdfStamper/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PdfStamper) {
      root.PdfStamper = {};
    }
    root.PdfStamper.BlockchainConfig = factory(root.PdfStamper.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BlockchainConfig model module.
   * @module SphereonSDKPdfStamper/model/BlockchainConfig
   * @version 1.0
   */

  /**
   * Constructs a new <code>BlockchainConfig</code>.
   * The Blockchain configuration
   * @alias module:SphereonSDKPdfStamper/model/BlockchainConfig
   * @class
   * @param blockchainAnchors {Array.<module:SphereonSDKPdfStamper/model/BlockchainConfig.BlockchainAnchorsEnum>} The states at which to create a blockchain anchor. This can be the original file (before stamp)the stamped file, or both
   * @param proofConfigName {String} The blockchain proof configuration name to use. The name has to be created in the blockchain-proof API
   */
  var exports = function(blockchainAnchors, proofConfigName) {
    var _this = this;

    _this['blockchainAnchors'] = blockchainAnchors;
    _this['proofConfigName'] = proofConfigName;
  };

  /**
   * Constructs a <code>BlockchainConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKPdfStamper/model/BlockchainConfig} obj Optional instance to populate.
   * @return {module:SphereonSDKPdfStamper/model/BlockchainConfig} The populated <code>BlockchainConfig</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('blockchainAnchors')) {
        obj['blockchainAnchors'] = ApiClient.convertToType(data['blockchainAnchors'], ['String']);
      }
      if (data.hasOwnProperty('proofConfigName')) {
        obj['proofConfigName'] = ApiClient.convertToType(data['proofConfigName'], 'String');
      }
    }
    return obj;
  }

  /**
   * The states at which to create a blockchain anchor. This can be the original file (before stamp)the stamped file, or both
   * @member {Array.<module:SphereonSDKPdfStamper/model/BlockchainConfig.BlockchainAnchorsEnum>} blockchainAnchors
   */
  exports.prototype['blockchainAnchors'] = undefined;
  /**
   * The blockchain proof configuration name to use. The name has to be created in the blockchain-proof API
   * @member {String} proofConfigName
   */
  exports.prototype['proofConfigName'] = undefined;


  /**
   * Allowed values for the <code>blockchainAnchors</code> property.
   * @enum {String}
   * @readonly
   */
  exports.BlockchainAnchorsEnum = {
    /**
     * value: "BEFORE_STAMP"
     * @const
     */
    "BEFORE_STAMP": "BEFORE_STAMP",
    /**
     * value: "AFTER_STAMP"
     * @const
     */
    "AFTER_STAMP": "AFTER_STAMP"  };


  return exports;
}));


