/**
 * PDF stamper
 * The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements.    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 1.0
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKPdfStamper/ApiClient', 'SphereonSDKPdfStamper/model/Border', 'SphereonSDKPdfStamper/model/Connector', 'SphereonSDKPdfStamper/model/Point', 'SphereonSDKPdfStamper/model/StampComponent'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Border'), require('./Connector'), require('./Point'), require('./StampComponent'));
  } else {
    // Browser globals (root is window)
    if (!root.PdfStamper) {
      root.PdfStamper = {};
    }
    root.PdfStamper.BlockchainProofComponent = factory(root.PdfStamper.ApiClient, root.PdfStamper.Border, root.PdfStamper.Connector, root.PdfStamper.Point, root.PdfStamper.StampComponent);
  }
}(this, function(ApiClient, Border, Connector, Point, StampComponent) {
  'use strict';




  /**
   * The BlockchainProofComponent model module.
   * @module SphereonSDKPdfStamper/model/BlockchainProofComponent
   * @version 1.0
   */

  /**
   * Constructs a new <code>BlockchainProofComponent</code>.
   * An invisible component that does a blockchain registration
   * @alias module:SphereonSDKPdfStamper/model/BlockchainProofComponent
   * @class
   * @extends module:SphereonSDKPdfStamper/model/StampComponent
   * @param type {String} The discriminator type for serialization of the different components
   * @param proofConfigName {String} The blockchain proof configuration name to use
   */
  var exports = function(type, proofConfigName) {
    var _this = this;
    StampComponent.call(_this, type);

    _this['proofConfigName'] = proofConfigName;
  };

  /**
   * Constructs a <code>BlockchainProofComponent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKPdfStamper/model/BlockchainProofComponent} obj Optional instance to populate.
   * @return {module:SphereonSDKPdfStamper/model/BlockchainProofComponent} The populated <code>BlockchainProofComponent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      StampComponent.constructFromObject(data, obj);
      if (data.hasOwnProperty('blockchainAnchors')) {
        obj['blockchainAnchors'] = ApiClient.convertToType(data['blockchainAnchors'], ['String']);
      }
      if (data.hasOwnProperty('proofConfigName')) {
        obj['proofConfigName'] = ApiClient.convertToType(data['proofConfigName'], 'String');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(StampComponent.prototype);
  exports.prototype.constructor = exports;

  /**
   * The states at which to create a blockchain anchor. This can be the original file (before stamp)the stamped file, or both
   * @member {Array.<module:SphereonSDKPdfStamper/model/BlockchainProofComponent.BlockchainAnchorsEnum>} blockchainAnchors
   */
  exports.prototype['blockchainAnchors'] = undefined;
  /**
   * The blockchain proof configuration name to use
   * @member {String} proofConfigName
   */
  exports.prototype['proofConfigName'] = undefined;


  /**
   * Allowed values for the <code>blockchainAnchors</code> property.
   * @enum {String}
   * @readonly
   */
  exports.BlockchainAnchorsEnum = {
    /**
     * value: "BEFORE_STAMP"
     * @const
     */
    "BEFORE_STAMP": "BEFORE_STAMP",
    /**
     * value: "AFTER_STAMP"
     * @const
     */
    "AFTER_STAMP": "AFTER_STAMP"  };


  return exports;
}));


