/**
 * PDF stamper
 * The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements. The API also supports digital signatures (blue bar), blockchain registrations and filling out forms    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 1.0
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKPdfStamper/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PdfStamper) {
      root.PdfStamper = {};
    }
    root.PdfStamper.CertificateSettings = factory(root.PdfStamper.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CertificateSettings model module.
   * @module SphereonSDKPdfStamper/model/CertificateSettings
   * @version 1.0
   */

  /**
   * Constructs a new <code>CertificateSettings</code>.
   * The PDF Certificate signature settings
   * @alias module:SphereonSDKPdfStamper/model/CertificateSettings
   * @class
   * @param certificateVersion {String} The optional version of the certificate from the crypto-keys configuration to use. Can be the value 'latest' to automatically use the latest version. The certificate (version) has to be present in the crypto-keys API
   * @param cryptoKeysConfigName {String} The Crypto Keys configuration name to use. The name has to be created in the crypto-keys API
   * @param certificateName {String} The name of the certificate from the crypto-keys configuration to use. The certificate has to be present in the crypto-keys API
   */
  var exports = function(certificateVersion, cryptoKeysConfigName, certificateName) {
    var _this = this;

    _this['certificateVersion'] = certificateVersion;
    _this['cryptoKeysConfigName'] = cryptoKeysConfigName;
    _this['certificateName'] = certificateName;
  };

  /**
   * Constructs a <code>CertificateSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKPdfStamper/model/CertificateSettings} obj Optional instance to populate.
   * @return {module:SphereonSDKPdfStamper/model/CertificateSettings} The populated <code>CertificateSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('certificateVersion')) {
        obj['certificateVersion'] = ApiClient.convertToType(data['certificateVersion'], 'String');
      }
      if (data.hasOwnProperty('cryptoKeysConfigName')) {
        obj['cryptoKeysConfigName'] = ApiClient.convertToType(data['cryptoKeysConfigName'], 'String');
      }
      if (data.hasOwnProperty('certificateName')) {
        obj['certificateName'] = ApiClient.convertToType(data['certificateName'], 'String');
      }
    }
    return obj;
  }

  /**
   * The optional version of the certificate from the crypto-keys configuration to use. Can be the value 'latest' to automatically use the latest version. The certificate (version) has to be present in the crypto-keys API
   * @member {String} certificateVersion
   */
  exports.prototype['certificateVersion'] = undefined;
  /**
   * The Crypto Keys configuration name to use. The name has to be created in the crypto-keys API
   * @member {String} cryptoKeysConfigName
   */
  exports.prototype['cryptoKeysConfigName'] = undefined;
  /**
   * The name of the certificate from the crypto-keys configuration to use. The certificate has to be present in the crypto-keys API
   * @member {String} certificateName
   */
  exports.prototype['certificateName'] = undefined;



  return exports;
}));


