/**
 * PDF stamper
 * The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements.    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 1.0
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKPdfStamper/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PdfStamper) {
      root.PdfStamper = {};
    }
    root.PdfStamper.ContentRequest = factory(root.PdfStamper.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ContentRequest model module.
   * @module SphereonSDKPdfStamper/model/ContentRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>ContentRequest</code>.
   * Content request
   * @alias module:SphereonSDKPdfStamper/model/ContentRequest
   * @class
   * @param filename {String} Original filename
   * @param configIds {Array.<String>} A list of configuration ids that have to be applied during executing the job.
   * @param content {String} The file as a base64 encoded string
   */
  var exports = function(filename, configIds, content) {
    var _this = this;


    _this['filename'] = filename;
    _this['configIds'] = configIds;
    _this['content'] = content;
  };

  /**
   * Constructs a <code>ContentRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKPdfStamper/model/ContentRequest} obj Optional instance to populate.
   * @return {module:SphereonSDKPdfStamper/model/ContentRequest} The populated <code>ContentRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('variables')) {
        obj['variables'] = ApiClient.convertToType(data['variables'], {'String': 'String'});
      }
      if (data.hasOwnProperty('filename')) {
        obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
      }
      if (data.hasOwnProperty('configIds')) {
        obj['configIds'] = ApiClient.convertToType(data['configIds'], ['String']);
      }
      if (data.hasOwnProperty('content')) {
        obj['content'] = ApiClient.convertToType(data['content'], 'String');
      }
    }
    return obj;
  }

  /**
   * A map with key-values used to replace template variables in components.
   * @member {Object.<String, String>} variables
   */
  exports.prototype['variables'] = undefined;
  /**
   * Original filename
   * @member {String} filename
   */
  exports.prototype['filename'] = undefined;
  /**
   * A list of configuration ids that have to be applied during executing the job.
   * @member {Array.<String>} configIds
   */
  exports.prototype['configIds'] = undefined;
  /**
   * The file as a base64 encoded string
   * @member {String} content
   */
  exports.prototype['content'] = undefined;



  return exports;
}));


