/**
 * PDF stamper
 * The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements.    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 1.0
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKPdfStamper/ApiClient', 'SphereonSDKPdfStamper/model/Border', 'SphereonSDKPdfStamper/model/Connector', 'SphereonSDKPdfStamper/model/Point', 'SphereonSDKPdfStamper/model/StampComponent'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Border'), require('./Connector'), require('./Point'), require('./StampComponent'));
  } else {
    // Browser globals (root is window)
    if (!root.PdfStamper) {
      root.PdfStamper = {};
    }
    root.PdfStamper.HyperlinkComponent = factory(root.PdfStamper.ApiClient, root.PdfStamper.Border, root.PdfStamper.Connector, root.PdfStamper.Point, root.PdfStamper.StampComponent);
  }
}(this, function(ApiClient, Border, Connector, Point, StampComponent) {
  'use strict';




  /**
   * The HyperlinkComponent model module.
   * @module SphereonSDKPdfStamper/model/HyperlinkComponent
   * @version 1.0
   */

  /**
   * Constructs a new <code>HyperlinkComponent</code>.
   * An hyperlink component to stamp a hyperlink on a pdf
   * @alias module:SphereonSDKPdfStamper/model/HyperlinkComponent
   * @class
   * @extends module:SphereonSDKPdfStamper/model/StampComponent
   * @param type {String} The discriminator type for serialization of the different components
   * @param address {String} The hyperlink address
   * @param width {Number} The preferred width in pixels
   * @param height {Number} The preferred height in pixels
   */
  var exports = function(type, address, width, height) {
    var _this = this;
    StampComponent.call(_this, type);
    _this['address'] = address;
    _this['width'] = width;
    _this['height'] = height;
  };

  /**
   * Constructs a <code>HyperlinkComponent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKPdfStamper/model/HyperlinkComponent} obj Optional instance to populate.
   * @return {module:SphereonSDKPdfStamper/model/HyperlinkComponent} The populated <code>HyperlinkComponent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      StampComponent.constructFromObject(data, obj);
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('width')) {
        obj['width'] = ApiClient.convertToType(data['width'], 'Number');
      }
      if (data.hasOwnProperty('height')) {
        obj['height'] = ApiClient.convertToType(data['height'], 'Number');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(StampComponent.prototype);
  exports.prototype.constructor = exports;

  /**
   * The hyperlink address
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * The preferred width in pixels
   * @member {Number} width
   */
  exports.prototype['width'] = undefined;
  /**
   * The preferred height in pixels
   * @member {Number} height
   */
  exports.prototype['height'] = undefined;



  return exports;
}));


