/**
 * PDF stamper
 * The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements.    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 1.0
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKPdfStamper/ApiClient', 'SphereonSDKPdfStamper/model/InputResultLocation', 'SphereonSDKPdfStamper/model/PdfStamperJobRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InputResultLocation'), require('./PdfStamperJobRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.PdfStamper) {
      root.PdfStamper = {};
    }
    root.PdfStamper.PdfStamperJobResult = factory(root.PdfStamper.ApiClient, root.PdfStamper.InputResultLocation, root.PdfStamper.PdfStamperJobRequest);
  }
}(this, function(ApiClient, InputResultLocation, PdfStamperJobRequest) {
  'use strict';




  /**
   * The PdfStamperJobResult model module.
   * @module SphereonSDKPdfStamper/model/PdfStamperJobResult
   * @version 1.0
   */

  /**
   * Constructs a new <code>PdfStamperJobResult</code>.
   * The PDF Stamper job.
   * @alias module:SphereonSDKPdfStamper/model/PdfStamperJobResult
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>PdfStamperJobResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKPdfStamper/model/PdfStamperJobResult} obj Optional instance to populate.
   * @return {module:SphereonSDKPdfStamper/model/PdfStamperJobResult} The populated <code>PdfStamperJobResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('completionTime')) {
        obj['completionTime'] = ApiClient.convertToType(data['completionTime'], 'Date');
      }
      if (data.hasOwnProperty('jobId')) {
        obj['jobId'] = ApiClient.convertToType(data['jobId'], 'String');
      }
      if (data.hasOwnProperty('request')) {
        obj['request'] = PdfStamperJobRequest.constructFromObject(data['request']);
      }
      if (data.hasOwnProperty('jobStatus')) {
        obj['jobStatus'] = ApiClient.convertToType(data['jobStatus'], 'String');
      }
      if (data.hasOwnProperty('creationTime')) {
        obj['creationTime'] = ApiClient.convertToType(data['creationTime'], 'Date');
      }
      if (data.hasOwnProperty('inputResults')) {
        obj['inputResults'] = ApiClient.convertToType(data['inputResults'], [InputResultLocation]);
      }
      if (data.hasOwnProperty('updateTime')) {
        obj['updateTime'] = ApiClient.convertToType(data['updateTime'], 'Date');
      }
      if (data.hasOwnProperty('statusMessage')) {
        obj['statusMessage'] = ApiClient.convertToType(data['statusMessage'], 'String');
      }
      if (data.hasOwnProperty('queueTime')) {
        obj['queueTime'] = ApiClient.convertToType(data['queueTime'], 'Date');
      }
    }
    return obj;
  }

  /**
   * The completion date/time of this job in ISO 8601 format
   * @member {Date} completionTime
   */
  exports.prototype['completionTime'] = undefined;
  /**
   * The job id
   * @member {String} jobId
   */
  exports.prototype['jobId'] = undefined;
  /**
   * The request settings used during executing the PDF Stamper job
   * @member {module:SphereonSDKPdfStamper/model/PdfStamperJobRequest} request
   */
  exports.prototype['request'] = undefined;
  /**
   * The status of the job
   * @member {module:SphereonSDKPdfStamper/model/PdfStamperJobResult.JobStatusEnum} jobStatus
   */
  exports.prototype['jobStatus'] = undefined;
  /**
   * The creation date/time of this job in ISO 8601 format
   * @member {Date} creationTime
   */
  exports.prototype['creationTime'] = undefined;
  /**
   * The input(s) and result(s) streamlocation pairs
   * @member {Array.<module:SphereonSDKPdfStamper/model/InputResultLocation>} inputResults
   */
  exports.prototype['inputResults'] = undefined;
  /**
   * The last update date/time of this job in ISO 8601 format
   * @member {Date} updateTime
   */
  exports.prototype['updateTime'] = undefined;
  /**
   * A status message, which can be informational, warning or error. AA message here does not indicate an error per se
   * @member {String} statusMessage
   */
  exports.prototype['statusMessage'] = undefined;
  /**
   * The PDF Stamper queue date/time of this job in ISO 8601 format
   * @member {Date} queueTime
   */
  exports.prototype['queueTime'] = undefined;


  /**
   * Allowed values for the <code>jobStatus</code> property.
   * @enum {String}
   * @readonly
   */
  exports.JobStatusEnum = {
    /**
     * value: "CREATED"
     * @const
     */
    "CREATED": "CREATED",
    /**
     * value: "INPUTS_UPLOADED"
     * @const
     */
    "INPUTS_UPLOADED": "INPUTS_UPLOADED",
    /**
     * value: "PROCESSING"
     * @const
     */
    "PROCESSING": "PROCESSING",
    /**
     * value: "DONE"
     * @const
     */
    "DONE": "DONE",
    /**
     * value: "ERROR"
     * @const
     */
    "ERROR": "ERROR",
    /**
     * value: "DELETED"
     * @const
     */
    "DELETED": "DELETED"  };


  return exports;
}));


